// The list of contributing factors
// this can be used to filtr the query

const ContributingFactors = [
        { label: "0", value: "Not selected" },
        { label: "1", value: " Animal on Road - Domestic" },
        { label: "2", value: "Animal on Road - Wild" },
        { label: "3", value: "Backed without Safety" },
        { label: "4", value: "Changed Lane when Unsafe" },
        { label: "14", value: "Disabled in Traffic Lane" },
        { label: "15", value: "Disregard Stop and Go Signal" },
        { label: "16", value: "Disregard Stop Sign or Light" },
        { label: "17", value: "Disregard Turn Marks at Intersection" },
        { label: "18", value: "Disregard Warning Sign at Construction" },
        { label: "19", value: "Distraction in Vehicle" },
        { label: "20", value: " Driver Inattention" },
        { label: "21", value: "Drove Without Headlights" },
        { label: "22", value: "Failed to Control Speed" },
        { label: "23", value: "Failed to Drive in Single Lane" },
        { label: "24", value: "Failed to Give Half of Roadway" },
        { label: "25", value: "Failed to Heed Warning Sign" },
        { label: "26", value: "Failed to Pass to Left Safely" },
        { label: "27", value: "Failed to Pass to Right Safely" },
        { label: "28", value: "Failed to Signal or Gave Wrong Signal" },
        { label: "29", value: "Failed to Stop at Proper Place" },
        { label: "30", value: "Failed to Stop for School Bus" },
        { label: "31", value: "Failed to Stop for Train" },
        { label: "32", value: "Failed to Yield ROW - Emergency Vehicle" },
        { label: "33", value: "Failed to Yield ROW - Open Intersection" },
        { label: "34", value: "Failed to Yield ROW -Private Drive" },
        { label: "35", value: "Failed to Yield ROW - Stop Sign" },
        { label: "36", value: "Failed to Yield ROW - To Pedestrian" },
        { label: "37", value: "Failed to Yield ROW - Turning Left" },
        { label: "38", value: "Failed to Yield ROW - Turn on Red" },
        { label: "39", value: "Failed to Yield ROW - Yield Sign" },
        { label: "40", value: "Fatigued or Asleep" },
        { label: "41", value: "Faulty Evasive Action" },
        { label: "42", value: "Fire in Vehicle" },
        { label: "43", value: "Fleeing or Evading Police" },
        { label: "44", value: "Followed Too Closely" },
        { label: "45", value: "Had Been Drinking" },
        { label: "46", value: "Handicapped Driver (Explain in Narrative)" },
        { label: "47", value: "Ill (Explain in Narrative)" },
        { label: "48", value: "Impaired Visibility (Explain in Narrative)" },
        { label: "49", value: "Improper Start from Parked Position" },
        { label: "50", value: "Load Not Secured" },
        { label: "51", value: "Opened Door Into Traffic Lane" },
        { label: "52", value: "Oversized Vehicle or Load" },
        { label: "53", value: "Overtake and Pass Insufficient Clearance" },
        { label: "54", value: "Parked and Failed to Set Brakes" },
        { label: "55", value: "Parked in Traffic Lane" },
        { label: "56", value: "Parked without Lights" },
        { label: "57", value: "Passed in No Passing Lane" },
        { label: "58", value: "Passed on Right Shoulder" },
        { label: "59", value: "Pedestrian FTYROW to Vehicle" },
        { label: "60", value: "Unsafe Speed" },
        { label: "61", value: "Speeding - (Over Limit)" },
        { label: "62", value: "Taking Medication (Explain in Narrative)" },
        { label: "63", value: "Turned Improperly - Cut Corner on Left" },
        { label: "64", value: "Turned Improperly - Wide Right" },
        { label: "65", value: "Turned Improperly - Wrong Lane" },
        { label: "66", value: "Turned when Unsafe" },
        { label: "67", value: "Under Influence - Alcohol" },
        { label: "68", value: "Under Influence - Drug" },
        { label: "69", value: "Wrong Side - Approach or Intersection" },
        { label: "70", value: "Wrong Side - Not Passing" },
        { label: "71", value: "Wrong Way - One Way Road" },
        { label: "73", value: "Road Rage" },
        { label: "74", value: "Cell/Mobile Device Use - Talking" },
        { label: "75", value: "Cell/Mobile Device Use - Texting" },
        { label: "76", value: "Cell/Mobile Device Use - Other" },
        { label: "77", value: "Cell/Mobile Device Use - Unknown" },
        {
          label: "78",
          value:
            "Failed to slow or move over for vehicles displaying emergency lights"
        }
      ];
      
export default ContributingFactors;